import mlx.core as mx
import mlx.nn as nn

def coverage_loss(mu_net: mx.array, logvar_net: mx.array, z_target: mx.array) -> mx.array:
    """
    Computes the Negative Log-Likelihood (NLL) / Coverage Loss.
    Ensures that the truth point (z_target) from the God Encoder falls well
    within the probability net generated by Mamba's dynamic state.
    
    L_coverage = (z_target - mu_net)^2 / (2 * sigma_net^2) + log(sigma_net)
               = 0.5 * ( (z - mu)^2 / exp(logvar) ) + 0.5 * logvar
    """
    # Numerically stabilize logvar
    logvar_net = mx.clip(logvar_net, -20.0, 20.0)
    
    sq_err = mx.square(z_target - mu_net)
    var = mx.exp(logvar_net)
    
    quadratic_term = sq_err / var
    nll_per_dim = 0.5 * (quadratic_term + logvar_net)
    
    # We mean over all dimensions (Batch, SeqLen, z_dim) for stability
    return nll_per_dim.mean()

def momentum_continuity_loss(mu_trajectory: mx.array) -> mx.array:
    """
    L_momentum = 1 - cos(Delta mu_t, Delta mu_{t-1})
    """
    # mu_trajectory: (B, L, z_dim)
    B, L, _ = mu_trajectory.shape
    if L < 3:
        return mx.array(0.0)
        
    delta_mu = mu_trajectory[:, 1:, :] - mu_trajectory[:, :-1, :] # (B, L-1, z_dim)
    
    delta_t = delta_mu[:, 1:, :] # (B, L-2, z_dim)
    delta_t_minus_1 = delta_mu[:, :-1, :] # (B, L-2, z_dim)
    
    # Cosine similarity: (A dot B) / (|A| |B|)
    dot_product = (delta_t * delta_t_minus_1).sum(axis=-1)
    norm_t = mx.sqrt(mx.square(delta_t).sum(axis=-1) + 1e-8)
    norm_t_1 = mx.sqrt(mx.square(delta_t_minus_1).sum(axis=-1) + 1e-8)
    
    cos_sim = dot_product / (norm_t * norm_t_1)
    
    loss = (1.0 - cos_sim).mean()
    return loss



def decoder_reconstruction_loss(logits: mx.array, target_tokens: mx.array) -> mx.array:
    """
    L_recon = Cross Entropy Loss
    """
    loss = nn.losses.cross_entropy(logits, target_tokens, reduction='mean')
    return loss
